### ISSUE TITLE
Incomplete reponse

### ISSUE THREAD

**Issue by WGuethlein** [floh22/native-farsight-module#21]
To preface, this might be user error. When calling makeSnapshot, it returns an incomplete reponse (response below). The champions list returns an empty array.

Calling Code:
`
async function init() {
    var res = await farsight.connectToLeague();

    if(res && farsight.isReady()) {
        console.log("Farsight is ready!");
    }

    var timeout = setInterval(() => {
        if(!farsight.isReady() || !res) {
            res = farsight.connectToLeague();
        }
        if (res && farsight.isReady()) {
            var state = farsight.makeSnapshot();
            
            var gameTime = state.gameTime;
            var champions = state.champions;
            var inhibs = state.inhibitors;
            var other = state.other;
            var nextDrag = state.nextDragonType;

            var MSTime = convertToMinSec(gameTime);

            fs.writeFile("test.json", JSON.stringify(state), function(err) {
                if (err) {
                    console.log(err);
                }
            });
            
            console.log(state)
        }
    }
        , 2000);
}
`

Response:
`
{
	"champions": [],
	"jungle": [
		{
			"name": "",
			"displayName": "Dragon_Indicator_Fire.troy",
			"networkId": 1073742109,
			"objectIndex": 1190,
			"position": { "0": 9460, "1": -71.2406005859375, "2": 4784 },
			"team": 0,
			"isAlive": false,
			"health": -1.0406421075842335e34,
			"maxHealth": -1.3488673896216018e34,
			"mana": 462.53759765625,
			"maxMana": 528384.0625
		}
	],
	"turrets": [
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 82, 95, 48, 51, 95, 65
				]
			},
			"networkId": 1073741829,
			"objectIndex": 1136,
			"position": { "0": 10504, "1": 41, "2": 1029 },
			"team": 100,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 82, 95, 48, 50, 95, 65
				]
			},
			"networkId": 1073741830,
			"objectIndex": 1139,
			"position": { "0": 6919, "1": 43, "2": 1483 },
			"team": 100,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 100,
			"maxMana": 100
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 82, 95, 48, 50]
			},
			"networkId": 4294259305,
			"objectIndex": 566,
			"position": { "0": 6919, "1": 43, "2": 1483 },
			"team": 100,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 82, 95, 48, 51, 95, 65
				]
			},
			"networkId": 1073741832,
			"objectIndex": 1145,
			"position": { "0": 13866, "1": 38, "2": 4505 },
			"team": 200,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 55, 95, 65
				]
			},
			"networkId": 1073741831,
			"objectIndex": 1142,
			"position": { "0": 4281, "1": 86, "2": 1253 },
			"team": 100,
			"isAlive": true,
			"health": 3300,
			"maxHealth": 3300,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 52, 95, 65
				]
			},
			"networkId": 1073741836,
			"objectIndex": 1151,
			"position": { "0": 5048, "1": 43, "2": 4812 },
			"team": 100,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 100,
			"maxMana": 100
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 53]
			},
			"networkId": 4281636656,
			"objectIndex": 903,
			"position": { "0": 5846, "1": 44, "2": 6396 },
			"team": 100,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 82, 95, 48, 49, 95, 65
				]
			},
			"networkId": 1073741834,
			"objectIndex": 1147,
			"position": { "0": 13624, "1": 88, "2": 10572 },
			"team": 200,
			"isAlive": true,
			"health": 3300,
			"maxHealth": 3300,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 67, 95, 48, 50, 95, 65
				]
			},
			"networkId": 1073741844,
			"objectIndex": 1167,
			"position": { "0": 12611, "1": 88, "2": 13084 },
			"team": 200,
			"isAlive": true,
			"health": 2700,
			"maxHealth": 2700,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 82, 95, 48, 51]
			},
			"networkId": 4294050559,
			"objectIndex": 956,
			"position": { "0": 10504, "1": 41, "2": 1029 },
			"team": 100,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 82, 95, 48, 50, 95, 65
				]
			},
			"networkId": 1073741833,
			"objectIndex": 1146,
			"position": { "0": 13327, "1": 38, "2": 8226 },
			"team": 200,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 100,
			"maxMana": 100
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 53, 95, 65
				]
			},
			"networkId": 1073741835,
			"objectIndex": 1148,
			"position": { "0": 5846, "1": 44, "2": 6396 },
			"team": 100,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 67, 95, 48, 53, 95, 65
				]
			},
			"networkId": 1073741840,
			"objectIndex": 1163,
			"position": { "0": 8955, "1": 38, "2": 8510 },
			"team": 200,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 76, 95, 48, 50, 95, 65
				]
			},
			"networkId": 1073741848,
			"objectIndex": 1173,
			"position": { "0": 1512, "1": 42, "2": 6699 },
			"team": 100,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 100,
			"maxMana": 100
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 50]
			},
			"networkId": 4283433619,
			"objectIndex": 616,
			"position": { "0": 2177, "1": 89, "2": 1807 },
			"team": 100,
			"isAlive": true,
			"health": 2700,
			"maxHealth": 2700,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 76, 95, 48, 49]
			},
			"networkId": 4289606097,
			"objectIndex": 960,
			"position": { "0": 10481, "1": 88, "2": 13650 },
			"team": 200,
			"isAlive": true,
			"health": 3300,
			"maxHealth": 3300,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 67, 95, 48, 49]
			},
			"networkId": 4291633543,
			"objectIndex": 599,
			"position": { "0": 13052, "1": 88, "2": 12612 },
			"team": 200,
			"isAlive": true,
			"health": 2700,
			"maxHealth": 2700,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 49, 95, 65
				]
			},
			"networkId": 1073741838,
			"objectIndex": 1157,
			"position": { "0": 1748, "1": 88, "2": 2270 },
			"team": 100,
			"isAlive": true,
			"health": 2700,
			"maxHealth": 2700,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 67, 95, 48, 51, 95, 65
				]
			},
			"networkId": 1073741842,
			"objectIndex": 1165,
			"position": { "0": 11134, "1": 88, "2": 11207 },
			"team": 200,
			"isAlive": true,
			"health": 3300,
			"maxHealth": 3300,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 76, 95, 48, 49, 95, 65
				]
			},
			"networkId": 1073741852,
			"objectIndex": 1181,
			"position": { "0": 10481, "1": 88, "2": 13650 },
			"team": 200,
			"isAlive": true,
			"health": 3300,
			"maxHealth": 3300,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 82, 95, 48, 49]
			},
			"networkId": 4285010301,
			"objectIndex": 744,
			"position": { "0": 13624, "1": 88, "2": 10572 },
			"team": 200,
			"isAlive": true,
			"health": 3300,
			"maxHealth": 3300,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 67, 95, 48, 52]
			},
			"networkId": 4289189128,
			"objectIndex": 829,
			"position": { "0": 9767, "1": 38, "2": 10113 },
			"team": 200,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 67, 95, 48, 51]
			},
			"networkId": 4290986155,
			"objectIndex": 610,
			"position": { "0": 11134, "1": 88, "2": 11207 },
			"team": 200,
			"isAlive": true,
			"health": 3300,
			"maxHealth": 3300,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 51, 95, 65
				]
			},
			"networkId": 1073741837,
			"objectIndex": 1154,
			"position": { "0": 3651, "1": 91, "2": 3696 },
			"team": 100,
			"isAlive": true,
			"health": 3300,
			"maxHealth": 3300,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 50, 95, 65
				]
			},
			"networkId": 1073741839,
			"objectIndex": 1160,
			"position": { "0": 2177, "1": 89, "2": 1807 },
			"team": 100,
			"isAlive": true,
			"health": 2700,
			"maxHealth": 2700,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 67, 95, 48, 52, 95, 65
				]
			},
			"networkId": 1073741841,
			"objectIndex": 1164,
			"position": { "0": 9767, "1": 38, "2": 10113 },
			"team": 200,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 100,
			"maxMana": 100
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 67, 95, 48, 49, 95, 65
				]
			},
			"networkId": 1073741843,
			"objectIndex": 1166,
			"position": { "0": 13052, "1": 88, "2": 12612 },
			"team": 200,
			"isAlive": true,
			"health": 2700,
			"maxHealth": 2700,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 76, 95, 48, 51, 95, 65
				]
			},
			"networkId": 1073741847,
			"objectIndex": 1170,
			"position": { "0": 981, "1": 37, "2": 10441 },
			"team": 100,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 76, 95, 48, 51, 95, 65
				]
			},
			"networkId": 1073741850,
			"objectIndex": 1179,
			"position": { "0": 4318, "1": 38, "2": 13875 },
			"team": 200,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 55]
			},
			"networkId": 4282054172,
			"objectIndex": 944,
			"position": { "0": 4281, "1": 86, "2": 1253 },
			"team": 100,
			"isAlive": true,
			"health": 3300,
			"maxHealth": 3300,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 76, 95, 48, 51]
			},
			"networkId": 4288696573,
			"objectIndex": 839,
			"position": { "0": 4318, "1": 38, "2": 13875 },
			"team": 200,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 76, 95, 48, 50]
			},
			"networkId": 4289159275,
			"objectIndex": 1027,
			"position": { "0": 7943, "1": 38, "2": 13411 },
			"team": 200,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 76, 95, 48, 50]
			},
			"networkId": 4289159275,
			"objectIndex": 1027,
			"position": { "0": 7943, "1": 38, "2": 13411 },
			"team": 200,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 54, 95, 65
				]
			},
			"networkId": 1073741849,
			"objectIndex": 1176,
			"position": { "0": 1169, "1": 90.7349853515625, "2": 4287 },
			"team": 100,
			"isAlive": true,
			"health": 3300,
			"maxHealth": 3300,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [
					84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 76, 95, 48, 50, 95, 65
				]
			},
			"networkId": 1073741851,
			"objectIndex": 1180,
			"position": { "0": 7943, "1": 38, "2": 13411 },
			"team": 200,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 100,
			"maxMana": 100
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 76, 95, 48, 50]
			},
			"networkId": 4281537221,
			"objectIndex": 620,
			"position": { "0": 1512, "1": 42, "2": 6699 },
			"team": 100,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 76, 95, 48, 50]
			},
			"networkId": 4281537221,
			"objectIndex": 620,
			"position": { "0": 1512, "1": 42, "2": 6699 },
			"team": 100,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 51]
			},
			"networkId": 4283904517,
			"objectIndex": 827,
			"position": { "0": 3651, "1": 91, "2": 3696 },
			"team": 100,
			"isAlive": true,
			"health": 3300,
			"maxHealth": 3300,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 82, 95, 48, 51]
			},
			"networkId": 4284903505,
			"objectIndex": 998,
			"position": { "0": 13866, "1": 38, "2": 4505 },
			"team": 200,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 67, 95, 48, 53]
			},
			"networkId": 4288734622,
			"objectIndex": 639,
			"position": { "0": 8955, "1": 38, "2": 8510 },
			"team": 200,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 52]
			},
			"networkId": 4281575334,
			"objectIndex": 709,
			"position": { "0": 5048, "1": 43, "2": 4812 },
			"team": 100,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 67, 95, 48, 49]
			},
			"networkId": 4284044073,
			"objectIndex": 974,
			"position": { "0": 1748, "1": 88, "2": 2270 },
			"team": 100,
			"isAlive": true,
			"health": 2700,
			"maxHealth": 2700,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 50, 95, 82, 95, 48, 50]
			},
			"networkId": 4284563655,
			"objectIndex": 1073,
			"position": { "0": 13327, "1": 38, "2": 8226 },
			"team": 200,
			"isAlive": true,
			"health": 3600,
			"maxHealth": 3600,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [84, 117, 114, 114, 101, 116, 95, 84, 49, 95, 76, 95, 48, 51]
			},
			"networkId": 4281606739,
			"objectIndex": 1088,
			"position": { "0": 981, "1": 37, "2": 10441 },
			"team": 100,
			"isAlive": true,
			"health": 5000,
			"maxHealth": 5000,
			"mana": 0,
			"maxMana": 0
		}
	],
	"inhibitors": [
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [66, 97, 114, 114, 97, 99, 107, 115, 95, 84, 50, 95, 67, 49]
			},
			"networkId": 4294938399,
			"objectIndex": 852,
			"position": { "0": 11603.068359375, "1": 89, "2": 11667 },
			"team": 200,
			"isAlive": true,
			"health": 4000,
			"maxHealth": 4000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [66, 97, 114, 114, 97, 99, 107, 115, 95, 84, 49, 95, 76, 49]
			},
			"networkId": 4291968062,
			"objectIndex": 693,
			"position": {
				"0": 1169.275146484375,
				"1": 94.7349853515625,
				"2": 3573.222412109375
			},
			"team": 100,
			"isAlive": true,
			"health": 4000,
			"maxHealth": 4000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [66, 97, 114, 114, 97, 99, 107, 115, 95, 84, 49, 95, 67, 49]
			},
			"networkId": 4283048177,
			"objectIndex": 786,
			"position": { "0": 3203, "1": 92, "2": 3208 },
			"team": 100,
			"isAlive": true,
			"health": 4000,
			"maxHealth": 4000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [66, 97, 114, 114, 97, 99, 107, 115, 95, 84, 50, 95, 82, 49]
			},
			"networkId": 4280724495,
			"objectIndex": 837,
			"position": { "0": 13598.1416015625, "1": 89, "2": 11316.134765625 },
			"team": 200,
			"isAlive": true,
			"health": 4000,
			"maxHealth": 4000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [66, 97, 114, 114, 97, 99, 107, 115, 95, 84, 50, 95, 76, 49]
			},
			"networkId": 4284978128,
			"objectIndex": 628,
			"position": { "0": 11261, "1": 88, "2": 13659.9619140625 },
			"team": 200,
			"isAlive": true,
			"health": 4000,
			"maxHealth": 4000,
			"mana": 0,
			"maxMana": 0
		},
		{
			"name": "",
			"displayName": {
				"type": "Buffer",
				"data": [66, 97, 114, 114, 97, 99, 107, 115, 95, 84, 49, 95, 82, 49]
			},
			"networkId": 4287824865,
			"objectIndex": 1093,
			"position": { "0": 3454.878662109375, "1": 89, "2": 1241.762939453125 },
			"team": 100,
			"isAlive": true,
			"health": 4000,
			"maxHealth": 4000,
			"mana": 0,
			"maxMana": 0
		}
	],
	"other": [
		"Omitted": "but complete"
	],
	"gameTime": 8.398467063903809,
	"nextDragonType": "Fire",
	"benchmark": {
		"readObjectsMs": 1.3565000295639038,
		"fullUpdateMs": 2.504499912261963
	}
}
`

**Comment by floh22** [comment]
Did you pull the source from the repo or use the npm package? Incase you used the npm package, try using the source if possible, npm might be outdated. Otherwise try running the example and post what results that produces. If it still does not work, mind sharing your setup? As in OS and League Region

**Comment by WGuethlein** [comment]
This was with the npm package, I will test with source tomorrow and give follow-up.

**Comment by WGuethlein** [comment]
Pulling from source solved the issue, thanks.
