### ISSUE TITLE
Vanguard's effect on the farsight module

### ISSUE THREAD

**Issue by figyl** [floh22/native-farsight-module#47]
With the announcement of Vanguard coming to League I have my doubts about the relative safety of using the farsight module in the spectator mode of custom / tournament code games. Does anyone know if Riot's angle will remain the same about no anti-cheat during spectating?

**Comment by floh22** [comment]
Riot have not yet released any statement changing their stance on memory reading, though I would welcome any update from Riot through any channel.

From rumors and what I have been able to piece together, it is highly unlikely Farsight will continue working once 14.4 drops, which is the patch where Vanguard is expected to replace the current anti cheat.

Offsets will most likely not get updated to patch 14.4.
The repository will stay online and a warning will be added.

**Comment by figyl** [comment]
Understandable, thanks for the reply. 
RIP🕯️
