### ISSUE TITLE
13.5 offset bug (blue team total gold higher than actual total)

### ISSUE THREAD

**Issue by FireFoXz09** [floh22/native-farsight-module#5]
Blue team total gold gets added with another number, because it's always higher than the actual blue team gold the further the game advance.

**Comment by dcapape** [comment]
Check if this happens only sometimes. In that case, check if your Snapshot is getting more than 5 champions for that team. Some objects can be wrongly identified as Champions incorrectly (Shako, neeko, leblanc clones...)
